### ISSUE TITLE
Test262 integration with Flow

### ISSUE THREAD

**Issue by leobalter** [bocoup/test262#121]

**Comment by leobalter** [comment]
At this point it doesn't seem that Flow really filters any test file, it just runs everything and maintains a report of known failures: 

https://github.com/facebook/flow/blob/master/src/parser/test/test262_baseline.txt
https://github.com/facebook/flow/blob/master/src/parser/test/parse_test262.ml

They already maintain status for `features` that are not fully supported yet.

Follow up question: is it a goal for Flow to have an adaptor for test262-harness? I don't think so. Maybe improving the features flags will be the helpful step for them.

**Comment by rwaldron** [comment]
I believe the goal is for them to be able to filter on frontmatter values, specifically `features` (but ideally any, right?). So, _yes_, test262 is integrated, but Flow will benefit from the work we do to improve test262-harness and test262-stream

**Comment by spectranaut** [comment]
Open questions:
- [ ] Why does Flow run their parser on Test262? What do they want to learn/catch from running these tests? What was the motivating use case?
- [ ] And now -- how do they use the results in test262_baseline.txt?
- [ ] What output saved to test262_baseline.txt file is noise and what output is signal? Otherwise stated: Would if help Flow to filter Test262 -- are there some tests that are irrelevant for them to parse, and if so, which ones?

**Comment by jugglinmike** [comment]
> Why does Flow run their parser on Test262? What do they want to learn/catch
> from running these tests? What was the motivating use case?

My guess is that since Flow is a superset of JavaScript, the maintainers are interested in ensuring their parser accepts all valid JavaScript programs.Rejections would generally hold true as well, but they'll have to be careful because Test262 could at any time accept negative syntax tests that happen to describe Flow type annotations. This ["forbidden extension"](https://tc39.github.io/ecma262/#sec-forbidden-extensions) is particularly relevant:

> The Syntactic Grammar must not be extended in any manner that allows the token : to immediately follow source text that matches the BindingIdentifier nonterminal symbol.  

Of course, my speculation is no substitute for the perspective of the maintainers themselves. I just thought maybe this guess might help you form the question. So please do ask--just give me a Coke if I was right.

**Comment by spectranaut** [comment]
> What output saved to test262_baseline.txt file is noise and what output is signal? Otherwise stated: Would if help Flow to filter Test262 -- are there some tests that are irrelevant for them to parse, and if so, which ones?

This question was partially answered by Rick! Flow should fail to parse files with frontmatter:
```
Negative:
  phase: early
```

**Comment by labond** [comment]
We'll connect with Flow to get feedback on @spectranaut's notes

**Comment by spectranaut** [comment]
We talked to Marshall. Test262 has so far been used to catch quite a few parser errors. The ones left in test262_baseline.txt are a mix of:
* some real errors to fix in Flow
* some very low priority errors in Flow (like html comments)
* some false positive that could be fixed once we have this new frontmatter tag (https://github.com/tc39/test262/issues/1254)

I asked if there was any other kind of filtering that might be useful, or if he could tell us more about the tests they simply don't care about (or test that fall under bullet two above). Seems like there is not a clear answer. But, he does find the feature tags very useful for summarizing and is interested in being able to ignore failures on not-yet-implemented features.

As an aside -- Flow expect to add another step of use of test262. After parsing, they plan to test the AST output and make sure the results is the same as the original test262  file.
